### ISSUE TITLE
Build no longer bzip2 but still has bz2 extension.

### ISSUE THREAD

**Issue by MicahZoltu** [monero-project/meta#372] opened 2019-07-18 07:51 UTC
https://downloads.getmonero.org/linux64 redirects to https://dlsrc.getmonero.org/cli/monero-linux-x64-v0.14.1.0.tar.bz2.  However, the file at that location is _not_ a bzip2 file like the file extension suggests.  Instead, it is a gzipped file.  Trying to extract it with `tar --extract --bzip2 --file=monero-linux-x64-v0.14.1.0.tar.bz2` will fail with `tar` telling you that the file is not a bzip2 file.  Extracting with `--gzip` however will work.

**Comment by dEBRUYNE-1** [comment] 2019-07-18 08:36
This should be fixed in the upcoming v0.14.1.1 release.

**Comment by erciccione** [comment] 2019-07-18 09:43
This is a duplicate of monero-project/monero#5730.

Also please see the [issue on GitLab](repo.getmonero.org/monero-project/monero-site/issues/964)

**Comment by jonathancross** [comment] 2019-07-18 21:39
Hi all, I submitted a PR to fix this issue: #5764 - reviews welcome. :-)

**Comment by jonathancross** [comment] 2019-09-04 14:49
Now that monero-project/monero#5764 is merged, the next release should be bzip2.

**Closed** 2020-03-09 21:41 UTC
